### ISSUE TITLE
CharsWhileIn - documentation inconsistency

### ISSUE THREAD

**Issue by james64** [com-lihaoyi/fastparse#207]
According to both scaladoc string [here](https://github.com/lihaoyi/fastparse/blob/master/fastparse/src/fastparse/package.scala#L614) and my intuition given its name `CharsWhileIn("a")` should behave as `CharsWhileIn("a",0)`.

However according to both sourcecode [here](https://github.com/lihaoyi/fastparse/blob/master/fastparse/src/fastparse/internal/MacroImpls.scala#L520) and my experience it behaves as `CharsWhileIn("a",1)`.

**Comment by arteme** [comment]
Fixed here, it seems:
https://github.com/lihaoyi/fastparse/commit/e71b61ffe10a0189b48cff02bb8eb7c7ca734009
