### ISSUE TITLE
Publish for Scala Native

### ISSUE THREAD

**Issue by raboof** [com-lihaoyi/fastparse#215]
Fastparse 2 is [not released for Scala Native](http://www.lihaoyi.com/fastparse/#2.0.4)

This depends on the release of [Scala Native 0.4.0](https://github.com/scala-native/scala-native/milestone/19).

**Comment by hepin1989** [comment]
scala native 0.4.0 is just released https://scala-native.readthedocs.io/en/v0.4.0/changelog/0.4.0.html

**Comment by lihaoyi** [comment]
This has happened
