### ISSUE TITLE
.opaque(...) produces misleading error messages

### ISSUE THREAD

**Issue by makkarpov** [com-lihaoyi/fastparse#228]
I have encountered a case when reported parser errors differ when using `opaque`'s: it adds false branch to 'expected' section, which is not actually expected.

A test case without `opaque`'s produces such error message, which is correct:

```
val Test = P( "A" ~/ "B" ~/ End )
println(Test.parse("AAB").get)

// Exception in thread "main" fastparse.core.ParseError: found "AB", expected "B" at index 1
// AAB
//  ^
```

However, when I add `opaque` to parsers, result becomes incorrect:

```
val Test = P( "A".opaque("a") ~/ "B".opaque("b") ~/ End )
println(Test.parse("AAB").get)

// Exception in thread "main" fastparse.core.ParseError: found "AB", expected b | a at index 1
// AAB
//  ^
```

As you can see, it adds branch `| a` to error message that is not possible to parse at that position.

**Comment by lihaoyi** [comment]
largely fixed in master, with one follow up fixed by https://github.com/com-lihaoyi/fastparse/pull/278
