### ISSUE TITLE
String Seq String can't accept

### ISSUE THREAD

**Issue by jacktok** [com-lihaoyi/fastparse#233]
i trying to use
```scala
val myString = Seq["test", "abc", "efg"]

def test[_: P] = StringIn(myString: _*).!
val result = fastparse.parse("test", test(_))
```

i got this
```
Error:(12, 26) Function can only accept constant singleton type
def test[_: P] = StringIn(myString : _*).!
```

**Comment by lihaoyi** [comment]
Probably going to call this the same issue as https://github.com/com-lihaoyi/fastparse/issues/298; it's not the same symptom, but it has the same workaround. We really should document it better
