### ISSUE TITLE
Please publish 2.1.3 for Scala 2.11

### ISSUE THREAD

**Issue by shawjef3** [com-lihaoyi/fastparse#234]
Only Fastparse 2.1.3 is available for Scala 2.13, whereas the last version of Fastparse published for Scala 2.11 is 2.1.2. Having to use fastparse 2.1.2 for Scala 2.11 but fastparse 2.1.3 for Scala 2.1.3 makes cross compiling unnecessarily difficult.

Publishing Fastparse 2.1.3 for Scala 2.11 would make cross compiling much easier.

**Comment by SethTisue** [comment]
Many Scala OSS libraries have dropped 2.11 from their crossbuilds. I'd suggest simply closing this ticket.

**Comment by shawjef3** [comment]
I still use 2.11 at work.

**Comment by lihaoyi** [comment]
Going to close this as a wontfix. Choosing different versions of libraries is a common requirement for cross-compilation, and comes with the territory if you want to cross-compile across 2.11-2.13. FastParse master only supports 2.12 and 2.13 right now, but feel free to re-compile it yourself with 2.11 if it makes your life easier
