### ISSUE TITLE
Packrat parser example (or implementation)

### ISSUE THREAD

**Issue by davips** [com-lihaoyi/fastparse#245]
I saw your comment about adding `Map[(Parser[_], String, Int)]` to every parser to have a packrat behavior, but I didn't get it.
Is there any way we can access your packrat attempt? (through code example, or as part of this library)

I know it is 30x slower than original fastparse2, but it would still be faster than the packrat from std lib.

**Comment by lihaoyi** [comment]
Probably not, it's lost in the mists of time. You'll have to try your own hand at adding such a feature
