### ISSUE TITLE
Scala 3 port

### ISSUE THREAD

**Issue by nightscape** [com-lihaoyi/fastparse#246]
Hi all,

I'm in the process of rewriting a library to use a more modern parser than scala-parser-combinator.
The choice currently comes down to fastparse or cats-parse.
fastparse is a little faster than cats-parse, but cats-parse is already compatible with Scala 3.
Now I'm wondering if there's any plans to port the macro part of fastparse over to the new Scala 3 macros? The comment on top of MacroImpl suggests that most functionality is related to inlining, which afaik is built into Scala 3.
Can anybody give a rough estimate of how much effort it would be to port fastparse to Scala 3?

Thanks!

**Comment by SethTisue** [comment]
There is a WIP PR at #262

**Comment by lefou** [comment]
Fixed by #271
