### ISSUE TITLE
Mention fix for scala 2.13.7

### ISSUE THREAD

**Issue by francisdb** [com-lihaoyi/fastparse#258]
Looks like all our fastparse definitions won't compile any more with scala 2.13.7

```scala
 identifier expected but '_' found.
[error]   private def wholeNumber[_: P]: P[Int] = P(CharIn("0-9").rep(1).!.map(_.toInt))
```

Our compiler flags:

```scala
      "-Xsource:3",
      "--target:11",
      "-feature",
      "-unchecked",
      "-deprecation",
      "-encoding",
      "UTF-8", // yes, this is 2 args
      "-language:existentials",
      "-language:higherKinds",
      "-language:implicitConversions",
      "-unchecked",
      "-Xlint:-unused,_"
```

something is mentioned here: https://github.com/scala/scala/pull/9712

But maybe the docs here could be updated showing how to fix these?

**Comment by lihaoyi** [comment]
@SethTisue IIRC we only made compilations fail when using eta expansion? Or did we make the use of underscore here a compile failure as well?

**Comment by SethTisue** [comment]
Under `-Xsource:3` it's a failure, as per scala/scala#9712

**Comment by bwbecker** [comment]
Replace the _ with any old identifier.  The documentation should change, though.

**Comment by lihaoyi** [comment]
The documentation has changed to `$`
