### ISSUE TITLE
Python 2.7 support dropped from actions/setup-python

### ISSUE THREAD

**Issue by ysthakur** [com-lihaoyi/fastparse#289]
Unfortunately, actions/setup-python dropped support for Python 2.7 on June 19 (see [issue/announcement](https://github.com/actions/setup-python/issues/672)), and the test-jvm job in the ci workflow uses it.

**Comment by lihaoyi** [comment]
Yeah, looks like we may have to drop that part of our CI. Probably OK, because we have a bunch of unit tests for PythonParse that do not required Python installed, and it's neither under active development nor is it a first-class supported module since it's just an example of using FastParse
